swagger: "2.0"
info:
  title: "User API"
  version: "1.0.0"
  description: "User API"
host: "user-api.company.com"
basePath: "/"
schemes:
- "https"
paths:
  /v1/create-user:
    post:
      summary: "Create a new user."
      operationId: "createUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Username and password."
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "405":
          description: "Invalid input"
  /log-in:
    post:
      summary: "Logs the user in."
      operationId: "LogIn"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  User:
    type: "object"
    required:
    - "username"
    - "password"
    properties:
      username:
        type: "string"
      password:
        type: "string"
